# Generated by Django 6.1.1 on 2026-09-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantemodels',
            name='telefono',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
