# Generated by Django 6.1.1 on 2026-09-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalderoPostre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('descripcion', models.CharField(max_length=250)),
                ('porcion', models.CharField(max_length=50)),
                ('extra', models.CharField(max_length=250)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CalderoSandwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('descripcion', models.CharField(max_length=250)),
                ('pan', models.CharField(max_length=75)),
                ('proteina', models.CharField(max_length=150)),
                ('extra', models.CharField(max_length=250)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
